/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ED;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Santos
 */
public class ABPJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ABPJFrame
     */
    public ABPJFrame() {
        initComponents();
        Criar();
    }
    ABP a;
    JButton[] botao;
    JLabel[] seta;
    JLabel in = new JLabel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelBotoes = new javax.swing.JPanel();
        Inserir = new javax.swing.JButton();
        Busca = new javax.swing.JButton();
        InOrder = new javax.swing.JButton();
        BTNLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Árvore Binaria de Pesquisa");
        setResizable(false);

        PainelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Inserir.setText("Inserir");
        Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirActionPerformed(evt);
            }
        });

        Busca.setText("Buscar");
        Busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaActionPerformed(evt);
            }
        });

        InOrder.setText("In-Ordem");
        InOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InOrderActionPerformed(evt);
            }
        });

        BTNLimpar.setText("Limpar");
        BTNLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Inserir)
                .addGap(54, 54, 54)
                .addComponent(Busca)
                .addGap(55, 55, 55)
                .addComponent(InOrder)
                .addGap(56, 56, 56)
                .addComponent(BTNLimpar)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inserir)
                    .addComponent(Busca)
                    .addComponent(InOrder)
                    .addComponent(BTNLimpar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirActionPerformed
         try{
             String s = JOptionPane.showInputDialog("Digite o valor desejado:");
             int valor = Integer.parseInt(s);
            
            if(a.vazia()){
                a.insere(valor);
                botao[0].setText(s);
                botao[0].setVisible(true);
            }else{
                if(valor < Integer.parseInt(botao[0].getText()) && " ".equals(botao[1].getText())){
                    a.insere(valor);
                    botao[1].setText(s);
                    botao[1].setVisible(true);
                    seta[0].setVisible(true);
                }else
                if(valor > Integer.parseInt(botao[0].getText()) && " ".equals(botao[2].getText())){
                    a.insere(valor);
                    botao[2].setText(s);
                    botao[2].setVisible(true);
                    seta[1].setVisible(true);
                }else
                if(valor < Integer.parseInt(botao[0].getText()) && valor < Integer.parseInt(botao[1].getText()) && " ".equals(botao[3].getText())){
                    a.insere(valor);
                    botao[3].setText(s);
                    botao[3].setVisible(true);
                    seta[2].setVisible(true);
                }else
                if(valor < Integer.parseInt(botao[0].getText()) && valor > Integer.parseInt(botao[1].getText()) && " ".equals(botao[4].getText())){
                    a.insere(valor);
                    botao[4].setText(s);
                    botao[4].setVisible(true);
                    seta[3].setVisible(true);
                }else
                if(valor > Integer.parseInt(botao[0].getText()) && valor < Integer.parseInt(botao[2].getText()) && " ".equals(botao[5].getText())){
                    a.insere(valor);
                    botao[5].setText(s);
                    botao[5].setVisible(true);
                    seta[4].setVisible(true);
                }else
                if(valor > Integer.parseInt(botao[0].getText()) && valor > Integer.parseInt(botao[2].getText()) && " ".equals(botao[6].getText())){
                    a.insere(valor);
                    botao[6].setText(s);
                    botao[6].setVisible(true);
                    seta[5].setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null,"    ÁRVORE LIMITADA\nNão há espaço na tela!");
                }
             
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e );
        }
    }//GEN-LAST:event_InserirActionPerformed

    private void BuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaActionPerformed
            try{
             int o = Integer.parseInt(JOptionPane.showInputDialog("Digite o valor a ser buscado:"));
             
             for(int i = 0; i<7 ; i++){
                 botao[i].setBackground(Color.LIGHT_GRAY);
             }
             
             for(int i = 0; i<7 ; i++){
                if(botao[i].getText()!= " " && o == Integer.parseInt(botao[i].getText())){
                    botao[i].setBackground(Color.green);
                    break;
                }else if(i == 6){
                    JOptionPane.showMessageDialog(null, "Valor não contido na árvore!");
                }
                
             }
            
            
            }catch(Exception e){
        }
    }//GEN-LAST:event_BuscaActionPerformed

    private void InOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InOrderActionPerformed
        String n = a.exibeInOrdem();
        
        in.setVisible(true);
        in.setText("In-Ordem: "+n);
        
        
    }//GEN-LAST:event_InOrderActionPerformed

    private void BTNLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimparActionPerformed
        Criar();
    }//GEN-LAST:event_BTNLimparActionPerformed
    
    
    
    public void Criar(){
        a = new ABP();
        botao = new JButton[7];
        seta = new JLabel[6];
        in.setVisible(false);
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
                                   
            for(int i=0 ; i< 7; i++){
                botao[i] = new JButton();
                
                switch(i){
                    case 0:
                        botao[i].setBounds(290,60,50,50);
                        break;
                    case 1:
                        botao[i].setBounds(210,160,50,50);
                        seta[i-1] = new JLabel(new ImageIcon("src//Imagem//setae.jpg"));
                        seta[i-1].setBounds(255, 110, 50, 50);
                        seta[i-1].setVisible(false);
                        jPanel1.add(seta[i-1]);
                        break;
                    case 2:
                        botao[i].setBounds(370,160,50,50);
                        seta[i-1] = new JLabel(new ImageIcon("src//Imagem//setad.jpg"));
                        seta[i-1].setBounds(325, 110, 50, 50);
                        seta[i-1].setVisible(false);
                        jPanel1.add(seta[i-1]);
                        break;
                    case 3:
                        botao[i].setBounds(160,260,50,50);
                        seta[i-1] = new JLabel(new ImageIcon("src//Imagem//setae.jpg"));
                        seta[i-1].setBounds(185, 210, 50, 50);
                        seta[i-1].setVisible(false);
                        jPanel1.add(seta[i-1]);
                        break;
                    case 4:
                        botao[i].setBounds(260,260,50,50);
                        seta[i-1] = new JLabel(new ImageIcon("src//Imagem//setad.jpg"));
                        seta[i-1].setBounds(235, 210, 50, 50);
                        seta[i-1].setVisible(false);
                        jPanel1.add(seta[i-1]);
                        break;
                    case 5:
                        botao[i].setBounds(320,260,50,50);
                        seta[i-1] = new JLabel(new ImageIcon("src//Imagem//setae.jpg"));
                        seta[i-1].setBounds(345, 210, 50, 50);
                        seta[i-1].setVisible(false);
                        jPanel1.add(seta[i-1]);
                        break;
                    case 6:
                        botao[i].setBounds(420,260,50,50);
                        seta[i-1] = new JLabel(new ImageIcon("src//Imagem//setad.jpg"));
                        seta[i-1].setBounds(395, 210, 50, 50);
                        seta[i-1].setVisible(false);
                        jPanel1.add(seta[i-1]);
                        break;
                    
                }
                botao[i].setText(" ");
                botao[i].setVisible(false);
                botao[i].setBackground(Color.LIGHT_GRAY);
                botao[i].setForeground(Color.black);
                botao[i].setRolloverEnabled(false);
                botao[i].setFocusTraversalPolicyProvider(false);
                botao[i].setFont(new Font("Tahoma",Font.BOLD,15));
                jPanel1.add(botao[i]); // adiciona botão ao painel
            }
             in.setFont(new Font("Tahoma",Font.BOLD,15));
             in.setBackground(Color.WHITE);
             in.setForeground(Color.black);
             jPanel1.add(in);
             jPanel1.setVisible(true);
             in.setBounds(5,5,300,40);
            jPanel1.revalidate();//método para atualizar o painel 
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABPJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABPJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLimpar;
    private javax.swing.JButton Busca;
    private javax.swing.JButton InOrder;
    private javax.swing.JButton Inserir;
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
